### PR TITLE
Print, CSV, and JSON

### LINKED ISSUE #5: PDF output
We have the json output ready but need to research how to convert the json to CSV and PDF.
Create CSS to handle printing of the tables.

### LINKED ISSUE #6: CSV output
Research tools, client and server side, to generate CSV from json.

### PR DESCRIPTION
**Pull request by awolfe76**
- Created script to allow for download of CSV files (works in IE as well)
- Modified table 3-1 layout to make it easier to create the CSV
- Created print styles for the table to allow for easy printing (instead of generating a PDF)

Closes #5 
Closes #6

### CODE REVIEW

**Comment by awolfe76** [comment]
In addition to the Print, CSV, and JSON the tables are now rendering correctly with REAL DATA. :smile: 

To get a preview before merging you can check out -
http://awolfe76.github.io/hmda-viz-prototype/aggregate/2013/alabama/anniston-oxford/3-1/
http://awolfe76.github.io/hmda-viz-prototype/aggregate/2013/nebraska/omaha-council-bluffs/3-1/

Those are the 2 MSA's that we have real data for. I modified the json files manually to account for issues #45 and #44 for now.

Also @Kibrael it looks there the data is being duplicated from 'Minority Status>Other, Including Hispanic' into all of the Applicant Incomes. But census data resets and is correct. See the screenshot.
duplicate-data

I created #46 for it.

Closes #25

**Comment by lesgou** [comment]
This is :+1: !
Wondering if it is possible to "freeze pane" the page? So that the top row is visible as you scroll through the data?

Also, the last column of the print version seems to be cutting off.

**Comment by awolfe76** [comment]
Hey @lesgou, want to create issues for those 2 things? We can look at ways to keep the table header and for the column getting cut off on print, yeah, I think we should fix it. :wink:

**Comment by awolfe76** [comment]
This adds the contents of cf-framework to the repo. This is done so that someone can more easily get the project up and running locally; without requiring `yo cf` and the dependencies for running it.

It also adds proper 3-1.json format and rendering.

@cfpb/cf-team-admin - any suggestions/recommendations on maybe doing this a little differently? Seems like a lot to check into the repo but wanted to make it simple for someone to get this up and running. Do you recommend checking in the source so that someone can clone, quickly run Grunt, and start Jekyll to serve the pages? Or should we leave the source of CF out of the repo and require `yo cf` to get going? In the README I could then specify what files then should choose not to overwrite when that runs, like `Gruntfile.js` for example. (yes, i need to create the README :smile:)

**Comment by awolfe76** [comment]
@lesgou - try the print again please - http://awolfe76.github.io/hmda-viz-prototype/aggregate/2013/alabama/anniston-oxford/3-1/

**Comment by feomike** [comment]
@awolfe76 what are the chances that the download file has a name consistent w/ the table?  i think right now the download file is named 'download.csv' or something.  if not now, can we put in another version which ties the file name to the table/content selected name or something?  i think it would help users.

**Comment by awolfe76** [comment]
@feomike - i don't think there is any reliable way of doing this. Stackoverflow has many, many articles about it. Chrome has a download attribute that you can use but it requires 2 clicks. One to generate the file, and another then to download it with the correct filename. 

Not sure what you mean by 'put in another version'. But Chrome does something like that. Click the button once and its 'download.csv'. Click again and it's 'download(2).csv'. But to do that in the javascript is really the same as changing the filename completely.

I'll dig a bit more, but it doesn't look like there is a clean client-side solution.

**Comment by awolfe76** [comment]
@ascott1 @contolini @Scotchester 
@cfpb/cf-team-admin - any suggestions/recommendations on maybe doing versioning the framework (or not) a little differently? Seems like a lot to check into the repo but wanted to make it simple for someone to get this up and running. Do you recommend checking in the source so that someone can clone, quickly run Grunt, and start Jekyll to serve the pages? Or should we leave the source of CF out of the repo and require yo cf to get going? In the README I could then specify what files to choose not to overwrite when that runs, like Gruntfile.js for example. (yes, i need to create the README :smile:)

**Comment by feomike** [comment]
@awolfe76 bummer, totally makes sense though; don't go further on this.

**Comment by Scotchester** [comment]
@awolfe76 Hey, sorry we missed your earlier attempt to get our attention on this thread.

`yo cf` is only meant to be run once, at the very start of a project. After that, your project's Gruntfile and structure should evolve to suit your needs, and you shouldn't need/want to update "the framework" as it is given in the generator.

Ideally, the CF stuff wouldn't be checked into the repo, and new folks pulling this down for the first time should just have to run `npm install` (which has post-install tasks of `bower install` and `grunt:compile-cf`) and then `grunt` for the initial build.

But I understand the desire for people to get up and running quickly, and it's not a big deal to have the CF source in the repo. The important thing about doing that is making sure all of the third party license exceptions are listed in `TERMS.md` (see the cfgov-refresh repo's example).

Make sense?

**Comment by awolfe76** [comment]
@Scotchester Yep. Makes perfect sense. Plan on walking through the process tomorrow to double check it and update the `README`. 

I'll remove the `src` from the repo too.

Thanks for the help!

**Pull request merged**
