### PR TITLE
Table updates

### PR DESCRIPTION
**Pull request by awolfe76**
This has all of 3-1 for 2012 and 2013, a sample for 3-2, and a sample for 4-1 and 4-2.

3-2: http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/alabama/anniston-oxford/3-2/
4-1: http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/colorado/colorado-springs/4-1/
4-2: http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/colorado/colorado-springs/4-2/

### CODE REVIEW

**Comment by awolfe76** [comment]
Now has a mustache partial for the table banners (shared across all tables).

@lesgou @Kibrael - when you get a chance take a look at the urls above and let me know if we are :+1:

**Comment by awolfe76** [comment]
(TOTAL) added and WE HAVE COMMAS! :boom:

**Comment by awolfe76** [comment]
@lesgou - check out these for the TOTAL:
http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/colorado/colorado-springs/4-1/
http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/colorado/colorado-springs/4-2/

And commas should be on all (including 3-x).

**Comment by lesgou** [comment]
Yes!  commas!

So, because i'm a pain, the "totals" in the top section are bolded.  Should the totals in the bottom section also be bolded? Or the ones in the top section not bolded?

**Comment by awolfe76** [comment]
Can you grab a screen shot for me? I don't see any difference in them (all bold).
Or the URL?

**Comment by lesgou** [comment]
image

**Comment by awolfe76** [comment]
Hmm, I don't see that at all. Are you looking at 4-1 or 4-2? 
Is that in one of the URLs above?

**Comment by lesgou** [comment]
Yes, using the links above.  It comes out fine in firefox.  But chrome and IE both hav ethem non bolded.

**Comment by awolfe76** [comment]
@lesgou - have a look again please.

**Comment by lesgou** [comment]
It's all good!  in chrome and IE.  :+1:

**Pull request merged**
