### PR TITLE
Footnotes for 3-1

### PR DESCRIPTION
**Pull request by awolfe76**
Added the pages for footnotes for 2012 and 2013:
http://awolfe76.github.io/hmda-viz-prototype/footnotes/2013/
http://awolfe76.github.io/hmda-viz-prototype/footnotes/2012/

Added the footnotes to 3-1:
http://awolfe76.github.io/hmda-viz-prototype/aggregate/2013/alabama/anniston-oxford/3-1/

Also, only 2013 works now. I removed 2012 to make the build faster for now. Can add it back at anytime by changing the `.gitignore` and Jekylls `_config.yml`.

@lesgou @Kibrael let me know if these are good.

### CODE REVIEW

**Comment by awolfe76** [comment]
Now also has the report date for 3's and 4's.

**Comment by awolfe76** [comment]
And footnotes for 3-2.

**Comment by awolfe76** [comment]
Footnotes for 4 too.

**Comment by lesgou** [comment]
For the footnotes in 3-2, please remove footnotes 30 and 31 from page one, the first set of Mean and Median.

**Comment by lesgou** [comment]
image
image
image
image
image

**Comment by lesgou** [comment]
image
image
image
image

image
image

**Comment by lesgou** [comment]
I have reviewed the:
1)  Footnotes for 2012, 2013
2)  Footnotes and hyperlinks for tables 3-1, 3-2, and all of 4
3)  Report generated dates for tables 3 and 4

@awolfe76 @Kibrael I think that's all for me now, unless I am missing anything.
Awaiting whatever else you push my way.

**Comment by awolfe76** [comment]
Awesome. Thanks.

**Pull request merged**
